### ISSUE TITLE
OpenXmlPackage.Clone() does not copy PackageProperties

### ISSUE THREAD

**Issue by jordan-hemming** [OfficeDev/Open-XML-SDK#1150]
**Description**

Calling OpenXmlPackage.Clone() does not copy the PackageProperties to the returned clone of the package.

**Information**

- DocumentFormat.OpenXml Version: 2.16

**Repro**

```csharp
using (var original = WordprocessingDocument.Create("test.docx", WordprocessingDocumentType.Document))
{
    original.AddMainDocumentPart();
    original.PackageProperties.Title = "My Document";
    var clone = original.Clone("clone.docx");
    if (clone.PackageProperties.Title != original.PackageProperties.Title)
    {
        throw new Exception("Clone's package properties do not match.");
        // clone.PackageProperies.Title == null
    }
}
``` 
**Expected**

I would have expected the PackageProperties to have been copied over to the clone, along with the rest of the package content.

**Comment by ThomasBarnekow** [comment]
@jordan-hemming, how are you using the `PackageProperties`? I've been working with the SDK since 2014 and never used them.

**Comment by jordan-hemming** [comment]
@ThomasBarnekow, I'm using them to set document metadata like Title, Author and Version.

Specifically, I'm loading a "template" document from a MemoryStream, appending some content to it and making changes to the PackageProperties, then calling Clone() to save those changes to a file.

**Comment by ThomasBarnekow** [comment]
@jordan-hemming, here are a few thoughts:

- The mechanism you use (`PackageProperties`) is provided by the `System.IO.Packaging.Package` class and not the Open XML SDK. Looking at another issue that was reported, you might have to dispose the `OpenXmlPackage` (e.g., `WordprocessingDocument`) to have those changed properties written to it.
- If you open the `WordprocessingDocument` on a `MemoryStream`, it would anyhow be better to close that document (e.g., by leaving the scope of the using statement) and then save the `MemoryStream` to a file, e.g., using `File.WriteAllBytes`.

Instead of using the `PackageProperties`, could you also see what happens if you open the corresponding `OpenXmlPart` and change the properties in that part? Using the `PackageProperties` looks like it provides some shortcut that might not work in this case.

**Comment by jordan-hemming** [comment]
Hi @ThomasBarnekow.

Given the relatively small number of properties involved, I've opted to work around the problem by manually setting them after I do a clone.

Since this doesn't seem to be a problem with the Open-XML-SDK itself I'm going to close the issue.

Thanks.
