### ISSUE TITLE
How to Add a Custom Font from URL/PATH in Open XML 

### ISSUE THREAD

**Issue by saifullah18** [OfficeDev/Open-XML-SDK#1152]
![image](https://user-images.githubusercontent.com/31733917/170034035-daefc458-d385-4bf2-a429-9963ce6d8e72.png)

see how to pss the font URL in this Document.

**Comment by twsouthwick** [comment]
@saifullah18 feel free to link the question here, but I'm going to close this as it's not an SDK issue

**Comment by jiangjiji** [comment]
Is there any information about how to add an embed font?

**Comment by mikeebowen** [comment]
Hi @jiangjiji, usage questions should go to stackoverflow.com or our discussions page. This SO post might help the embedded fonts question:  [How can I embed any file type into Microsoft Word using OpenXml 2.0](https://stackoverflow.com/questions/3322247/how-can-i-embed-any-file-type-into-microsoft-word-using-openxml-2-0)

**Comment by jiangjiji** [comment]
Thanks for helping. But I really got stuck with embedding fonts. 

It seems that the.ttf format just can't be directly embedded in documents. (Maybe because of copyright issues, Google fonts can only be installed and not edited.)

And then, I found out that Microsoft Office changes the.ttf file type to the.fntdata type to embed a font, even though the font file isn't editable.

So how can we generate a.fntdata file? There's incredibly limited information available on the internet. If anyone had any information, it would be a huge help in filling this hole in font embedding knowledge.

**Comment by jiangjiji** [comment]
https://github.com/kiwiwings/poi-font-mbender

I have found a useful project to embedd fonts.
