### ISSUE TITLE
Doesn't work in .Net

### ISSUE THREAD

**Issue by KurtIO** [OfficeDev/Open-XML-SDK#1188]
I recently used an amazingly effective MS tool for upgrading a WPF .Net Framework app to .Net 6.  Everything worked perfect-perfect except for all of my (too many to contemplate rewriting) reports I created using OpenXML. 

doc.Save causes: [System.IO.IOException: 'Entries cannot be opened multiple times in Update mode

File.Copy(sourceWordTemplate, tempReportPath, true);
using (WordprocessingDocument wordDoc = WordprocessingDocument.Open(tempReportPath, true))
{
      MainDocumentPart mainPart = wordDoc.MainDocumentPart;
      XmlDocument doc = new XmlDocument();
      XmlDocument xnRow = new XmlDocument();
      doc.Load(mainPart.GetStream());

      // Building of the report which includes replacing text in the source doc, 
      // looping through, removing and adding table nodes and rows etc... 
      // nowhere in the report building is the word Stream used.

      doc.Save(mainPart.GetStream(FileMode.Create, FileAccess.Write));
      wordDoc.Close();
}
Any ideas?

_Originally posted by @KurtIO in https://github.com/OfficeDev/Open-XML-SDK/issues/909#issuecomment-1060068306_

**Comment by twsouthwick** [comment]
You need to dispose the stream when you're loading it. This wasn't needed in .NET Framework, but is in .NET Core due to changes in the System.IO.Compression library used. However, this is not an issue with the OpenXml library (or the .NET runtime), but is rather an issue with your code that is not disposing the stream after use. You should always dispose streams; even if it seems to work without doing so, it is part of the Stream contract (except MemoryStream which explicitly says it does not need to be disposed).

Try the following:

```csharp
using DocumentFormat.OpenXml.Packaging;
using System.Xml;

using (WordprocessingDocument wordDoc = WordprocessingDocument.Open(tempReportPath, true))
{
    XmlDocument doc = new XmlDocument();

    var mainPart = wordDoc.MainDocumentPart;

    if (mainPart is null)
    {
        throw new InvalidOperationException("No main part");
    }

    using (var stream = mainPart.GetStream())
    {
        doc.Load(stream);
    }

    // Building of the report which includes replacing text in the source doc, 
    // looping through, removing and adding table nodes and rows etc... 
    // nowhere in the report building is the word Stream used.

    using (var stream = mainPart.GetStream(FileMode.Create, FileAccess.Write))
    {
        doc.Save(stream);
    }
}
```

**Comment by KurtIO** [comment]
OMG it worked @twsouthwick thank you, thank you, thank you. Months of work just became minutes...
