### ISSUE TITLE
Source of MainDocumentPart class

### ISSUE THREAD

**Issue by Barrent** [OfficeDev/Open-XML-SDK#1213]
Hi,

Where can I find source of MainDocumentPart class and other classes listed in attributes of WordprocessingDocument class? 

Created a fork and changed assembly name of DocumentFormat.OpenXml to OpenSource.DocumentFormat.OpenXml to make it possible to load different versions of Open XML at the same time, but build fails due to unresolved classes.

##[error]src\DocumentFormat.OpenXml\Packaging\WordprocessingDocument.cs(18,28): Error CS0246: The type or namespace name 'MainDocumentPart' could not be found (are you missing a using directive or an assembly reference?)

Also it tries to restore DocumentFormat.OpenXml nuget package during build of DocumentFormat.OpenXml project. Where is it configured?

**Comment by hunyu** [comment]
Hi Barrent

MainDocumentPart is generated, you can find it under Dependencies/Analyzers/DocumentFormat.OpenXml.Generator.PartGenerator (see attached image)
![image](https://user-images.githubusercontent.com/69320868/193660886-c2b504fa-e956-4cbf-8a08-b43f9a9ff9e3.png)

To see this generated source, create another fork and build the solution without renaming assembly name.

Regarding renaming assembly, there is an old MSDN post [How to rename assemblies and project folders](https://social.msdn.microsoft.com/Forums/en-US/d4133fb7-57e1-44f2-a319-a63e7921ff0a/how-to-rename-assemblies-and-project-folders?forum=csharpide) provided detail steps how it can be done. I believed with generated codes it just makes the renaming assembly that much trickier. 

If you are still unable to compile the project after following the steps mentioned, you can post your question under https://stackoverflow.com/questions/tagged/visual-studio. Since, the error you encountered is not directly related to Open-XML-SDK itself.

**Comment by Barrent** [comment]
Thank you so much!

**Comment by hunyu** [comment]
Hi Barrent

I will mark the issue as closed.
