### ISSUE TITLE
Add documentation for using package sources

### ISSUE THREAD

**Issue by twsouthwick** [OfficeDev/Open-XML-SDK#149]
Some users are not familiar with NuGet package sources, so we should add some documentation to the README for this.

**Comment by Will-Gregg** [comment]
The following text was added to the readme in PR #151 

The Latest Builds

Where to get the Nuget package

The NuGet package for Open XML SDK is currently available as a custom feed on MyGet. You can trust this package source, since the custom feed is locked and only this project feeds into the source.

How to install the Nuget package

The package you want to install is DocumentFormat.OpenXml. See https://dotnet.myget.org/gallery/open-xml-sdk 

The package feed or the package source is specified by the feed URL. Depending on your version of Visual Studio, choose the appropriate feed URL from the table below. 

Table 1: The latest builds are available via a MyGet feed

Client                                                            Feed URL
NuGet V3 (Visual Studio 2015+)                  https://dotnet.myget.org/F/open-xml-sdk/api/v3/index.json
NuGet V2 (Visual Studio 2012+)                  https://dotnet.myget.org/F/open-xml-sdk/api/v2

Specify the package source via a configuration option. For more info, see https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior. Note that usually a NuGet.config file is placed in the directory and the configuration options are added there to ensure the sources are persisted in the version control.

Install the package. The Install-Package command considers the package source either via configuration or argument. (If you have trouble installing the package, try restarting Visual Studio. Package sources could be cached and changes you've made to any NuGet.config files may not be detected.)

PM> Install-Package DocumentFormat.OpenXml 

PM> Install-Package DocumentFormat.OpenXml -Source https://dotnet.myget.org/F/open-xml-sdk/api/v3/index.json 

Note: This example is for Visual Studio 2015 and later.

**Comment by ethier** [comment]
This is great.

Install-Package DocumentFormat.OpenXml -Source https://dotnet.myget.org/F/open-xml-sdk/api/v3/index.json

This doesn't work though. Is there a delay here? Just want to confirm whether the documentation is correct or whether it's just a matter of time before it's resolved.

**Comment by ClareMSYanGit** [comment]
I added the version. (see below) It seems to work for me. Can you confirm if it works for you? If it does, then I'll update the README instruction.
PM> Install-Package DocumentFormat.OpenXml -Version 2.7.0-vnext0061 -Source https://dotnet.myget.org/F/open-xml-sdk/api/v3/index.json

**Comment by Ivan-Grishkov** [comment]
Hello, Could someone explain, why do you use MyGet instead of Nuget? Do you plan to push 2.7.* builds to https://www.nuget.org/packages/OpenXMLSDK-MOT/ ? When?

**Comment by twsouthwick** [comment]
Hi @Ivan-Grishkov . This is common practice for CI builds. MyGet is a way of hosting a private feed so you have complete control over it. NuGet is a public feed that anyone and everyone can push to. For instance, that package you link to is **not** an official package and not put up or supported by the Office team (AFAIK). We are definitely looking into pushing a package to NuGet, but for now, adding this package source will get you unblocked. Please be aware that when a package is listed on NuGet.org, it is the `Owner` field that shows you you really owns it, not the `Authors` - ie, the `Authors` field is just a field that anything can be put into.

**Comment by twsouthwick** [comment]
@tomjebo I've reached out to the listed owner of that package so we can figure out where it's coming from.

**Comment by ranjithvenkatesh** [comment]
"Moss and Lichens" provides the NuGet packages for OpenXMLSDK-MOT on demand. I long back used Open XML and I liked it and started providing the packages on NuGet.
