### ISSUE TITLE
Latest update on NuGet

### ISSUE THREAD

**Issue by EatonZ** [OfficeDev/Open-XML-SDK#158]
Hi, can you please publish the latest update to NuGet? I am in eager need of a fix in release 2.7 and NuGet has been showing the old version for several day now.

https://www.nuget.org/packages/OpenXMLSDK-MOT/

Thank you!

**Comment by tomjebo** [comment]
@EatonZ If this is urgent for you, I will do this in the morning (Sunday), otherwise I will do this on Monday if you can wait. We currently do it manually which is more involved and also need to build a release package instead of the debug one the automated build creates.  Sorry for the inconvenience. Still a couple of wrinkles in the process to iron out. :(

**Comment by EatonZ** [comment]
@tomjebo Thanks for the response. This is not urgent, so do it whenever you can. Just wanted to make sure that it wasn't overlooked.

**Comment by tomjebo** [comment]
@EatonZ The 2.7.0 nuget package has been uploaded to the myget feed: 
https://dotnet.myget.org/feed/open-xml-sdk/package/nuget/DocumentFormat.OpenXml 

Please let me know if you have any problems.

**Comment by EatonZ** [comment]
@tomjebo Thank you - should I use that one instead of the one I linked originally? That one is still old.

**Comment by tomjebo** [comment]
@EatonZ if you want the 2.7.0 release, that link or the command shown on that page: 

Install-Package DocumentFormat.OpenXml -Version 2.7.0 

will retreive it.

**Comment by EatonZ** [comment]
I just added your MyGet to my feeds and I got it.

Why is there a dependency on "NuGet.CommandLine"? Seems strange to have that included now when 2.6.1 didn't need it.

**Comment by tomjebo** [comment]
I accidentally added that dependency when manually creating the package. I will rebuild tomorrow and re-upload. Should be faster this time. Sorry.

**Comment by tomjebo** [comment]
@EatonZ I've rebuilt and a new package should be uploaded by late morning. Again, sorry about the dependency.

**Comment by twsouthwick** [comment]
@EatonZ Also be aware that we found an issue with this when validating documents when launched from an assembly that enforces strong names. We have a fix (see #160), but you'll need to wait until we get that uploaded if that's a blocker for you

**Comment by EatonZ** [comment]
@twsouthwick Thanks for letting me know. That actually might impact me. Upload when you have all fixes in place - thanks!

**Comment by tomjebo** [comment]
@EatonZ the v2.7.1 release is deployed to nuget (myget feed) and this includes the fixes for the issues @twsouthwick  discussed above. This is the latest release and the one you should be using now.

**Comment by tomjebo** [comment]
@twsouthwick Thank you for helping work through the CI build and Validate problems!

**Comment by EatonZ** [comment]
@tomjebo Thanks - did you intend to publish as "prerelease"? It only shows up when I ask it to "Include prereleases".

**Comment by tomjebo** [comment]
@EatonZ it shows up for me in VS package manager without the include pre-release checkbox.

**Comment by EatonZ** [comment]
Looks like I may have been too quick, it's there now. Everything appears fine, thanks again!

**Comment by tomjebo** [comment]
@EatonZ ok, glad to hear it.  you may have had one of our 2.7.1 prerelease builds in your nuget cache.

**Comment by EatonZ** [comment]
@tomjebo Looks like the newest version isn't on NuGet yet.
Also, your release notes say you upgraded to the latest System.IO.Packaging 4.4.0, but it's actually 4.4.1 now.

**Comment by twsouthwick** [comment]
The release notes were accurate when we upgraded, but apparently there has been an update recently. There are possibly a few fixes in the 4.4.1 release that will fix some Xamarin issues. I'll see if we need to update to it. The final build is available for 2.8.0 with System.IO.Packaging 4.4.0, but hasn't made it onto NuGet itself yet (the package is available via MyGet and we're working on getting it to NuGet). If we upgrade to System.IO.Packaging 4.4.1 it will be for a 2.8.1 release.

In the future, can you open a new issue instead of a previous? This was one to release 2.7 - it makes it easier to have dedicated issues for things (ie this was reopened to update to 2.8.0).

Thanks!

**Comment by EatonZ** [comment]
I'll make sure to do that next time!

Will upgrading System.IO.Packaging to 4.4.1 in my project break anything with OpenXML, or is it advised to not upgrade it?

**Comment by twsouthwick** [comment]
Shouldn't break anything. We're following semantic versioning, so patch updates shouldn't break anything (if it does, report it and we can see if it's us or the packaging lib). You should be able to upgrade with minor version changes as well - just don't revert to an earlier minor version as APIs may be missing. See http://semver.org for more info.

**Comment by EatonZ** [comment]
Thanks!
