### ISSUE TITLE
Create a supported platform list for the library

### ISSUE THREAD

**Issue by twsouthwick** [OfficeDev/Open-XML-SDK#168]
With the release of the library for .NET 4.5 and .NET Standard 1.3, there have been a number of questions about support on specific platforms. This issue is to track the creation of a supported platform list so people can easily see which platform is supported. Since .NET Standard is a fairly new concept, this should help people translate the abstract concept of the standard into the more pragmatic question of "is this supported where I need it".

As an example we should start fleshing this list out (I've added the ones I know):

 Platform | Minimum Version 
--------|---------
 .NET Framework | 4.5 
.NET Core | 1.0
UWP | 
Mono | 
Xamarin iOS |
Xamarin Android |

Please leave a comment if you have tried v2.7.1+ on one of these platforms and if you encountered any issues

**Comment by prairiesnpr** [comment]
I'm unable to compile in release mode with UWP.  I receive an ILT0005 error.  This is with VS2017RC and NETCore.UniversalWindowsPlatform 5.3.0. Get the same error with 2.7.1 or 2.7.2 -vnext0023.  Remove OpenXml or compile in debug and the app will compile.

Error is:
\.nuget\packages\microsoft.net.native.compiler\1.6.0\tools\Microsoft.NetNative.targets(691,5): error : ILT0005: \.nuget\packages\microsoft.net.native.compiler\1.6.0\tools\x64\ilc\Tools\nutc_driver.exe @"\obj\x64\Release\ilc\intermediate\MDIL\FirearmDb.rsp"' returned exit code 1

**Comment by MattWhilden** [comment]
@prairiesnpr 
I work on the .NET Runtme and Compiler team. I suspect that the issue with your build is related to our over eager reflection analysis of the OpenXml binary. Fortunately, there are ways to give hints to the compiler for just such a scenario.

Can you try adding this directive:
` <Assembly Name="DocumentFormat.OpenXml" Dynamic="Auto"/>`

To this file in your project:  
`Properties\Default.rd.xml`

Because this short cuts some parts of our analysis you may see new runtime issues, it's hard to say without trying it out for your scenario.

If you discover that works for you it may be beneficial to have the directive rolled into the OpenXml nuget package as a Library rd.xml file. Some more reading about that is available [here](https://blogs.msdn.microsoft.com/dotnet/2014/05/23/net-native-deep-dive-making-your-library-great/)

**Comment by prairiesnpr** [comment]
After a few nights of trying different directives I actually was able to get the app to compile and function correctly.  The directive that finally worked for me was <Assembly Name="DocumentFormat.OpenXml" Dynamic="All" />.  Using Auto would compile, but I would get runtime errors with any call to the framework.

**Comment by MattWhilden** [comment]
Happy to hear you're unblocked. I presume markdown ate your directive tag :-)

**Comment by aworx** [comment]
Just to clarify why the above solution works for anyone interested. 
There are two issues. First is the one that prevents compilation. 
The first solution with <Assembly Name="DocumentFormat.OpenXml" Dynamic="Auto"/> solves that one.
The second one that is more tricky is revealing itself only when in Release since the compiler removes any types not used, so GetTypeOf returns null (used in OpenXML internal method CreateInstance). This causes any AddPart method throwing exceptions. 
The second solution <Assembly Name="DocumentFormat.OpenXml" Dynamic="All" /> from @prairiesnpr solves both issues.
