### ISSUE TITLE
FieldCode is fragmented

### ISSUE THREAD

**Issue by rainierpaul** [OfficeDev/Open-XML-SDK#195]
When getting fieldcodes using

`document.MainDocumentPart.RootElement.Descendants(Of FieldCode)()`

FieldCode  is fragmented  when Word put the instruction text in multiple  <w:instrText>. 

the xml looks like these
<w:r>
		<w:rPr>
			<w:b />
		</w:rPr>
		<w:fldChar w:fldCharType="begin" />
	</w:r>
	<w:r>
		<w:rPr>
			<w:b />
		</w:rPr>
		<w:instrText xml:space="preserve"> MERGEFIELD CHIL</w:instrText>
	</w:r>
	<w:r w:rsidRPr="00611B99">
		<w:rPr>
			<w:b />
			<w:szCs w:val="24" />
		</w:rPr>
		<w:instrText>D2__Person_1_First_Name</w:instrText>
	</w:r>
	<w:r>
		<w:rPr>
			<w:b />
		</w:rPr>
		<w:fldChar w:fldCharType="separate" />
	</w:r>
	<w:r>
		<w:rPr>
			<w:b />
		</w:rPr>
		<w:fldChar w:fldCharType="end" />
	</w:r>
 
I am getting two separate fieldcode

- MERGEFIELD CHIL
- D2_Person_1_First_Name

Instead of just one MERGEFIELD CHILD2_Person_1_First_Name

![fieldcodes](https://cloud.githubusercontent.com/assets/12826656/24689289/d705714c-1a08-11e7-98ee-4efce15ff58b.png)

**Comment by tomjebo** [comment]
Hi @rainierpaul, the FieldCode class is tied to the w:instrText element. And because the instruction text for that field has varied formatting, there are two elements for the one text string.  Descendants is very literal in that it only looks for elements that fit the type T that you pass. It looks like what you're asking for here is an enhancement to the framework specifically to handle these scenarios. Do you agree? I see an opportunity if you'd (or someone would) like to come up with a solution and submit a PR. We'll review it for addition to the Framework.

**Comment by twsouthwick** [comment]
@rainierpaul Were you able to come up with a fix? If so, we could look at incorporating it into the library

**Comment by ThomasBarnekow** [comment]
@rainierpaul, @tomjebo, and @twsouthwick In my mind, there is no fix in the Open XML SDK that you can make without changing its nature. The Open XML SDK is simply the lowest-level, strongly-typed API you can think of for producing and working with Open XML markup. Therefore, if Word or other tools produce complex markup (e.g., two `w:instrText` elements instead of one), you will have to pre-process or simplify that markup before doing whatever you want to do with this.

You should really have a look at the Open XML Power Tools. You would be surprised by how much cleanup or massaging is sometimes necessary before you can do what you'd actually want to do.

By the way, a number of years ago, @EricWhiteDev and I discussed whether it wouldn't make sense to include some higher-level abstractions into the SDK. However, at least at the time there was no desire on Microsoft's side to enhance the SDK in that way. I'm not sure whether that has changed.

**Comment by twsouthwick** [comment]
@rainierpaul Given what @ThomasBarnekow said, it does seem out of scope of the library. The SDK at this time is designed to help you manage the OpenXML schema in code. Please take a look at the Open XML Power Tools to see if it helps.
