### ISSUE TITLE
How to detect bold, italic and underlined characters using OpenXml

### ISSUE THREAD

**Issue by maninwindow** [OfficeDev/Open-XML-SDK#199]
I have Microsoft Excel files which contain bold, italic and underlined texts or characters. I need to detect those characters and  surround them by proper HTML tags. Is that possible to detect those texts using OpenXml?
e.g.
Input:

> This is a conttent contains **bold**, _italic_ and underlined (Github richtext editor has no underline decoration) characters.

Expected output:

`This is a conttent contains <b>bold</b>, <i>italic</i> and <u>underlined</u> characters.`

**Comment by robertmuehsig** [comment]
In general Text in OpenXml is more or less always inside a Paragraph, this paragraph can hold one or more Run-Elements and each Run-Element can be decorated with [Run-Properties](https://msdn.microsoft.com/en-us/library/documentformat.openxml.spreadsheet.runproperties%28v=office.14%29.aspx?f=255&MSPPError=-2147217396). Via the Run-Properties you should see the "Bold"/"Italic" etc. styling.

Be aware that some styling information can be applied via a Style - I'm not 100% sure if the element itself has always the full styling information applied on the Run-Element.

**Comment by ThomasBarnekow** [comment]
As noted in another case (see #188), GitHub issues are not the way to ask "how-to" questions. You should rather go to [stackoverflow.com](http://stackoverflow.com/questions/tagged/openxml), where you find questions and answers tagged with "openxml" or "openxml-sdk".

Further, the Open XML SDK provides a very low-level API with strongly typed classes representing Open XML elements such as paragraphs, runs, run properties, and such like. The README also mentions the Open XML PowerTools, which use Linq to XML instead of the strongly typed classes to work with those Open XML elements. You will find examples of how at least Word documents are transformed into HTML.

To work with either the strongly typed classes or Linq to XML, you need a solid understanding of Open XML itself. In your case, you should look at [shared string tables](http://www.datypic.com/sc/ooxml/s-sml-sharedStringTable.xsd.html) and specifically the `ssml:si`, `ssml:r`, `ssml:rPr`, `ssml:b`, `ssml:i`, `ssml:u`, and `ssml:t` elements.

If you write "This content contains **bold**, _italic_ and underlined characters." (where "underlined" is actually underlined), Excel would represent this **roughly** as follows:
```
<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <si>
    <r>
      <t xml:space="preserve">This content contains </t>
    </r>
    <r>
      <rPr>
        <b/>
      </rPr>
      <t>bold</t>
    </r>
    <r>
      <t xml:space="preserve">, </t>
    </r>
    <r>
      <rPr>
        <i/>
      </rPr>
      <t>italic</t>
    </r>
    <r>
      <t xml:space="preserve"> and </t>
    </r>
    <r>
      <rPr>
        <u/>
      </rPr>
      <t>underlined</t>
    </r>
    <r>
      <t xml:space="preserve"> characters.</t>
    </r>
  </si>
</sst>
```
I simplified the markup to highlight the important elements. 

Getting the right string item (`<si>...</si>`) for your cell is a different matter, which requires knowledge of the Open XML standard and structure of the specific packages for WordprocessingDocuments, SpreadsheetDocuments, and PresentationDocuments.

**Comment by maninwindow** [comment]
@robertmuehsig  @ThomasBarnekow Thanks for your inspiration. Problem still not get solved. Let me post a stackoverflow question.

**Comment by ThomasBarnekow** [comment]
@twsouthwick and @tomjebo, I think we can close this now.

**Comment by twsouthwick** [comment]
Sounds good! @maninwindow Please let us know if you run into any SDK issues. Also, it would helpful for future users if you could link the SO question you create.
