### ISSUE TITLE
Merge documents with header section

### ISSUE THREAD

**Issue by juanperezADD** [OfficeDev/Open-XML-SDK#219]
We have a technical question about merging documents. We want to combine multiple documents, each one with a different header, in one document with a header that is a merge of the others documents.

Here is an example:

- Company document: This is a document that we want to reuse in multiple documents. It contains in its header the company name and common information.

- Report document: This document includes in its header the Company document and additional information like the title of the report and parameters to filter the data to display.

- Final document: The final result should be one document that contains the company and report information in the header section.

Currently, we have tried to do this example using DocumentBuilder and at the final document there is only one of the headers, instead of a merge of all. Is it possible to combine headers with Open XML SDK? Is there any technical limitation?

**Comment by twsouthwick** [comment]
@juanperezADD Can you add a repro with the current steps you are using? As far as any limitations there, the library should be able to handle that. This issue tracker is more for product issues with the library; questions should be asked on StackOverflow instead.

**Comment by ThomasBarnekow** [comment]
@juanperezADD, since you mentioned DocumentBuilder, you should address any issues with this component in the [Open-Xml-PowerTools](https://github.com/OfficeDev/Open-Xml-PowerTools) repo.

If your question is whether the Open XML SDK provides a function for merging headers, the answer is no, i.e., there is nothing like `mergedHeader = HeaderTools.Merge(header1, header2)`. The Open XML SDK lets you produce the markup for a header. However, it is your job to define what the markup should be (e.g., a number of paragraphs containing information sourced from different headers).

**Comment by twsouthwick** [comment]
Thanks, @ThomasBarnekow . This appears to be an external issue. @juanperezADD Please reopen with more details if this is not the case.
