### ISSUE TITLE
.NET Standard 2.0 support

### ISSUE THREAD

**Issue by igitur** [OfficeDev/Open-XML-SDK#226]
I notice that @twsouthwick is already working on it, but I wanted to create a stub issue.

**Comment by twsouthwick** [comment]
Yeah, I've got a branch with the changes. Waiting for AppVeyor to upgrade to Visual Studio 15.3

**Comment by igitur** [comment]
I saw that branch and already made a PR on it to enable 15.3.

**Comment by twsouthwick** [comment]
Before I submit a PR for this, we should determine if we need it. Since it support .NET Standard 1.3 there is no real value that I can see in supporting .NET Standard 2.0. You should be able to reference this library against from a .NET Standard 2.0 (or .NET Core 2.0) assembly without any special changes. Since each cross-compiled assembly in the package adds about 5mb, we should try to keep it as minimal as possible.

**Comment by robertmuehsig** [comment]
Using a lower .NET Standard version should result in a broader adoption. In case of the full .NET framework 2.0 requires .NET Framework 4.6.1, which is quite high. 
Whats the reason to support .NET Standard 2.0 if it runs just fine with .NET Standard 1.3?

**Comment by igitur** [comment]
Yeah, I wasn't aware that you can cross-reference between different .NET versions. I found @twsouthwick 's .NET Standard 2.0 prerelease in his MyGet feed and assumed that it had already been decided that a .NET Standard 2.0 build would eventually be included. If that's not the case, you can close this issue. 

For ClosedXML, I need to build on .NET Standard 2.0 (to use System.Drawing and other stuff), but I'll try to reference the .NET Standard 1.3 version.

**Comment by twsouthwick** [comment]
We can go ahead and close this issue then. I had started a branch with .NET Standard 2.0 to play around with some preview tooling with a multi-targeting library. Since It doesn't appear to be necessary, I'll close this issue. If you find a reason why you'd need it, we can readdress it then.
