### ISSUE TITLE
Docx into SQL Server table

### ISSUE THREAD

**Issue by brightworks** [OfficeDev/Open-XML-SDK#246]
Would it be possible with this tool to parse an existing Docx document and grab its data to send to a SQL Server database?

**Comment by ThomasBarnekow** [comment]
@brightworks Assuming "this tool" means the Open XML SDK, you can absolutely do this. This obviously assumes that you know what "its data" is and how you want to map that to the database.

For example, if you wanted to create one record per paragraph and have its contents (e.g., inner text without formatting) written to one column, you can do that. Your definition of "its data" obviously determines the amount of processing required to extract and generate what you want.

**Comment by brightworks** [comment]
Thank you for the quick response. This is really helpful.

**Comment by robertmuehsig** [comment]
As a "warning": The OpenXML element "graph" and the different parts can be overwhelming at the beginning. For such "extraction" scenarios we often use the [FlatOpc-Format](https://blogs.msdn.microsoft.com/ericwhite/2008/09/29/the-flat-opc-format/). The flat opc is basically a "flat" xml representations of all parts. Or even simpler: This gives you a giant string that represents the complete document. 
Now you could just use a XPath to select your desired content.

**Comment by ThomasBarnekow** [comment]
@robertmuehsig made a good point. There is no single approach to extracting data from an Open XML document. Depending on what exactly you want to extract, you would be looking at a single Open XML part, e.g., the `MainDocumentPart`, or multiple such parts, e.g., additionally multiple header and footer parts, style definitions part, numbering definitions part, settings part, etc. The Flat OPC format makes it easier to process those parts, e.g., using XSLT or Linq to XML. However, if all you are interested in is contained in the `MainDocumentPart`, you don't need the Flat OPC format.

Regardless of the approach you choose, you would always use the Open XML SDK to create a `WordprocessingDocument`, e.g., through:
```
using (WordprocessingDocument wordDocument = WordprocessingDocument.Open(path, true))
{
  [...]
}
```
Based on that, you can then create a Flat OPC `XDocument` or `string`, using
```
XDocument flatOpcDocument = wordDocument.ToFlatOpcDocument();
```
or
```
string flatOpcString = wordDocument.ToFlatOpcString();
```
The `XDocument` and `string` both represent the **whole** `WordprocessingDocument` with all its parts, some or many of which might not be relevant in your use case, though.

Alternatively, you can work with individual Open XML parts and their contents. If you want to do that, you can use two approaches. Firstly, you can work with the strongly typed classes (e.g., `Document`, `Body`, `Paragraph`, `Run`, `Text`) provided by the Open XML SDK. Secondly, you can use the [Open XML PowerTools](https://github.com/OfficeDev/Open-Xml-PowerTools) and Linq to XML. In both scenarios, however, you would use the Open XML SDK to get hold of the Open XML Parts, e.g., the `MainDocumentPart`:
```
MainDocumentPart part = wordDocument.MainDocumentPart;
```
Let's assume the following simplified XML in the `MainDocumentPart`. In Microsoft Word, that is a single "Hello World!" paragraph formatted using the built-in "Normal" style (which is implicit).
```
<w:document xmlns:w="...">
  <w:body>
    <w:p>
      <w:r>
        <w:t>Hello World!</w:t>
      </w:r>
    </w:p>
  </w:body>
</w:document>
```
Using the strongly typed classes, you could do something like this:
```
Document document = part.Document;  // Get root element
Text text = document.Descendants<Text>().First();  // Get text element;
string value = text.Text;  // Get content, i.e., "Hello World!"
```
Using the Open XML PowerTools, what we've done above would look like this:
```
XElement document = part.GetXDocument().Root;  // Get root element
XElement text = document.Descendants(W.t).First();  // Get text element
string value = text.Value;  // Get content, i.e., "Hello World!"
```
You might have noticed the `W.t`. This is an `XName` defined representing the `w:t` XML element. Thus, where the Open XML SDK provides classes (e.g., `Text`) for those XML elements (e.g., `w:t`), the Open XML Power Tools define `XName`s (e.g., `W.t`).

Note that all of the above approaches operate on a very low level of abstraction and you will need to understand the Open XML format very well in all cases. Some things that are very easy and straightforward when using Word automation can be surprisingly hard and complex on the Open XML level. However, working on the Open XML level is often one or two orders of magnitude faster than using Word automation.

I am using all of the above approaches in my development. I would definitely recommend you have a look the [Open XML PowerTools](https://github.com/OfficeDev/Open-Xml-PowerTools), because they contain some handy tools, e.g., the `MarkupSimplifier`, which let you preprocess the XML before doing your own extraction. Not all of the XML contained in those parts will be relevant for you but can get in the way of your extraction logic.

**Comment by twsouthwick** [comment]
@brightworks Since this question appears to have been answered, I'm going to close this issue. Please reopen if you feel like there is an issue with OpenXml that needs to be addressed.
