### ISSUE TITLE
WordprocessingDocument.Close() throwing IsolatedStorageException

### ISSUE THREAD

**Issue by DavidThi808** [OfficeDev/Open-XML-SDK#292]
I am building up a chart with 582 literal data points. When I call WordprocessingDocument.Close() I get an IsolatedStorageException.

This doesn't make sense to me because the OpenXML SDK, as I understand it, is totally self contained writing data to a stream. There's no calls to Office or anything else that could hit this issue.

- .NET Target: 4.5.1
- DocumentFormat.OpenXml Version: 2.0.5022.0

I can create an example if needed (what I have right now is part of a very large program). However, I'm hopeful someone will tell me that this is a known issue and what I can do to handle it.

**Comment by tarunchopra** [comment]
Hello Dave - The latest version of openxml is 2.7.2. Can you please upgrade to test the latest version and let us know if you are still hitting this issue ?

**Comment by DavidThi808** [comment]
Hi;

Good suggestion. I just updated and same problem with 2.7.2.

Any ideas? I don’t understand why this error can even occur as you’re just doing standard file I/O – correct?

Thanks – dave

**Comment by tarunchopra** [comment]
Hello Dave -

I just tested attached sample program and Close() worked just fine. Kindly have a look.

[Openxml-nuget.zip](https://github.com/OfficeDev/Open-XML-SDK/files/1468458/Openxml-nuget.zip)

Thanks.

**Comment by DavidThi808** [comment]
Thank you – I will. And if it works, change it to get the problem we have.

It may be 2 weeks before I can do this.

Thanks - dave

**Comment by tarunchopra** [comment]
Sure, will look forward to hearing from you.

**Comment by DavidThi808** [comment]
[OpenXML_chart_bug.zip](https://github.com/OfficeDev/Open-XML-SDK/files/1472542/OpenXML_chart_bug.zip)

Ok, I've got an example. In the attached Openxml-nuget2 runs our example from a command line app. Works fine.

But then run AddInMenuTest (it's a Word AddIn). This gets the error. So the error only occurs for large data sets when running as an Office AddIn.

Is this sufficient for your needs?

thanks - dave

**Comment by twsouthwick** [comment]
On .NET Framework, the System.IO.Packaging class is from WindowsBase which has some issues with isolated storage when you are updating a file of a certain size in appdomains don't have sufficient evidence (and possible other situations).

**Comment by DavidThi808** [comment]
Yes, it definitely occurs only for large enough files. And only when running as an AddIn. Which leads to the question, how do I get around this?
thanks - dave

**Comment by tarunchopra** [comment]
@twsouthwick : If it's a known issue; how can we get traction to get it addressed?

**Comment by twsouthwick** [comment]
@tarunchopra It is addressed in .NET Core. Modifying the code in WindowsBase is very difficult and doing so would add a new problem. On .NET Framework, IsolatedStorage is used and can encounter this issue, but on .NET Core, it is done in memory, and so some operations explode in memory rather than going to disk. A full fix for this in .NET Core would require streaming support for zip files, which is not available at the moment and no current plans. See https://github.com/dotnet/corefx/issues/20558 for the discussion on that issue

@DavidThi808 Something you can try is manually dropping the .NET Standard build of System.IO.Packaging into the deployment of code. This is definitely a hacky workaround, but it is where we're at right now. t may work on 4.5.1, but .NET Standard is only supported on 4.6+, so it may have issues in your current set up. Can you upgrade to 4.6?

**Comment by DavidThi808** [comment]
@twsouthwick - we can upgrade to 4.6 (I think). Would that make the problem go away? Or do I need to do that **plus** get the standard build of Packaging?

**Comment by twsouthwick** [comment]
At the moment, you need to do both. This may create an increase in working set, though, but I guess that's better than crashing.

**Comment by DavidThi808** [comment]
Would it be possible for me to contribute rewriting this to the standard OpenXML library? It seems to me if it's normal file I/O then there should be no limits like this.

??? - thanks - dave

**Comment by twsouthwick** [comment]
The limitation has to do with the `System.IO.Packaging` library works. A package is essentially a zip archive with a specific way of holding information. Thus, it depends on zip manipulation, so it's not really a straight forward file I/O due to how zipping occurs.

> contribute rewriting this to the standard OpenXML library

Not sure what you mean by the "standard OpenXML library", but we welcome contributions to this library and the .NET team welcomes contributions there. The issue is tracking down at which level is the bug - this one has to do with System.IO.Packaging. Feel free to open an issue at dotnet/corefx which is where System.IO.Packaging is developed.

**Comment by DavidThi808** [comment]
@twsouthwick - Can you please point me to the url where I can open this as an issue for dotnet/corefx?

**Comment by twsouthwick** [comment]
https://github.com/dotnet/corefx/issues

**Comment by DavidThi808** [comment]
@twsouthwick - What if I got the source to System.IO.Packaging and rewrote it to avoid this issue (probably using SHarpZipLib). Would your team then consider adding it in?

thanks - dave

**Comment by twsouthwick** [comment]
You'd have to bring that up on the CoreFx since they own System.IO.Packaging and we don't want a dependency on a fork of a framework dependency. Generally, though, CoreFX doesn't want to depend on any 3rd party libraries. The best way forward is to push on dotnet/corefx#20558 to get streaming zip support in the framework.

**Comment by DavidThi808** [comment]
Good points - thanks for your help - dave

**Comment by twsouthwick** [comment]
No problem. We're amassing issues that will hopefully give some good support for streaming support (I think I've found three so far). Did using the .NET Standard 1.3 version help?

**Comment by DavidThi808** [comment]
We decided to not use the .NET Standard 1.3 - we are worried about problems from using something different from the core lib. We can work around this for the moment.

But I am onboard with doing anything I can to get this fixed. I'd love to get streaming zip support for our DOCX/XLSX/PPTX generation too (we do that ourselves in our engine).

**Comment by twsouthwick** [comment]
The best thing to help keep that ball rolling will be to at least +1 the applicable comments in the issue I referenced above about zip streaming :)

**Comment by thetredev** [comment]
Just stumbled upon this error on a legacy .NET Framework 4.8.1 project I'm working on, which is a DLL addon for a tool, and I guess that tool itself sets the AppDomain, which my addon doesn't know about.

Is there any way to workaround this issue, or get the AppDomain info from the "parent application", or tell Windows "hey my DLL isn't the one, check this app instead for the AppDomain"?
