### ISSUE TITLE
Print powerpoint slides with notes not working

### ISSUE THREAD

**Issue by Saftpresse99** [OfficeDev/Open-XML-SDK#293]
**Description**

We are making Powerpoint documents from a web application for our customers with OpenXML. On some slides we add notes. The notes are displayed on the screen, but if we try to print the slides with notes, only the notes are printed if you select "print slides with notes" in the print layout setting. 

**Information**

- .NET Target: (NET Framework 4.7)
- DocumentFormat.OpenXml Version: (2.5.1 or 2.7.2)

**Repro**

We are using this code to create notes: https://stackoverflow.com/questions/32562130/how-to-add-notes-to-a-particular-slide-in-a-ppt 

**Observed**

Slides not printed, only notes.

**Expected**

Expected behavior is print slide content and below the notes.

**Comment by ThomasBarnekow** [comment]
This is not an issue with the Open XML SDK (for which you would open an issue here) but rather an issue with producing the correct Open XML markup (for which stackoverflow.com would be the right place).

When it comes to Open XML markup, you must understand what markup EXACTLY you need to produce in order to create the desired outcome. One way of determining what markup you need is to use PowerPoint to create a presentation that looks/prints exactly as desired. You can then use the Open XML SDK to create EXACTLY that markup.

As explained in responses to other "issues", the Open XML SDK is a very low-level SDK that provides no abstraction whatsoever and basically just helps you create Open XML markup directly, using strongly typed classes. You could also use Linq to XML as demonstrated in the PowerTools for Open XML to create the exact same output.

A final, stackoverflow.com type thought would be that you might not have set up your notes master correctly.

**Comment by Saftpresse99** [comment]
Hi,
thanks for your reply. I'm new to this. Do you have some links for setting up a notes master correctly?

**Comment by ThomasBarnekow** [comment]
@Saftpresse99, you should just google this. One result that might turn up is [this](https://www.teachucomp.com/notes-master-in-powerpoint-instructions/).

**Comment by twsouthwick** [comment]
@Saftpresse99 I'm closing this as this is not an issue with the SDK. Please let us know if you find any bugs in the SDK and please check out StackOverflow for help in how to use the SDK
