### ISSUE TITLE
Set Excel columns "AA" error

### ISSUE THREAD

**Issue by liu7923032** [OfficeDev/Open-XML-SDK#37]
I created a Excel document, "AA" data set, column "B" no data, and download the Excel abnormal

**Comment by EricWhiteDev** [comment]
Excel, more than the other two office client apps, is extremely particular about ordering of elements and attributes.  This is because it is extremely important to get good speed out of Excel when you have huge Worksheets.

Did you validate the document using the Open XML SDK validation functionality?

Take a look at the following screen-cast on Debugging Open XML when the Office Client Crashes

http://openxmldeveloper.org/blog/b/openxmldeveloper/archive/2013/05/30/screen-cast-debugging-open-xml-when-the-office-client-crashes.aspx
