### ISSUE TITLE
OpenXML  - workbook.xml.rels

### ISSUE THREAD

**Issue by mraz1337** [OfficeDev/Open-XML-SDK#392]
We have found the annoyance which doesn't allow the file to be opened on iOS/Mac OS xl\_rels\workbook.xml.rels 

Inside this file there is tag with Target Attribute

 <Relationship Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="/xl/styles.xml" Id="rId3"/>

OpenXML SDK adds this "/xl/" before filename.  
Excel after re-saving removes this "/xl/" and file can be opened on iOS.

Question: how to force OpenXML SDK to work as Excel does and NOT put this  "/xl/" into Target tag of  workbook.xml.rels?

**Comment by daniel-white** [comment]
Sounds like #221

**Comment by twsouthwick** [comment]
This is fixed in CoreFx, but hasn't been release yet. The fix has been merged into System.IO.Packaging and available in a CI build. The package is available here (not on NuGet yet): https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.IO.Packaging/4.5.0-preview1-26011-03 (or newer). Once it is released, we'll update the project to take a dependency on it. If you explicitly reference this package along with 2.8.1 of the SDK, it should work.

If you have issues, please reopen the issue and let us know what you're hitting.
