### ISSUE TITLE
Open xml does not open the Excel file

### ISSUE THREAD

**Issue by Umeshpatil0012** [OfficeDev/Open-XML-SDK#409]
I have open excel file in OpenXml Productivity Tool 2.5 and seen that the file has missing Properties child elements (Application, DocumentSecurity, ScaleCrop, HeadingPairs, TitlesOfParts, LinksUpToDate, SharedDocument, HyperlinksChanged, ApplicationVersion).
I have open the file using OpenXml library in C# it throws **FileFormatException**. But, when i open the file manually and save it and then open using OpenXml library in C# it works file.
How i add Properties child element in Excel file without opening in OpenXml library in C#.

**Comment by ThomasBarnekow** [comment]
@Umeshpatil0012 You essentially described the solution: open and save the file in Excel, assuming this is what you meant with "open the file manually and save it".

It seems your file somehow got corrupted, which is why the Open XML SDK throws that `FileFormatException`. Microsoft Office, however, can fix corrupted files in many cases. When saved, Excel (or Word and PowerPoint) will add certain standard parts that you would otherwise have to add explicitly yourself.

@twsouthwick While it would be nice if the Open XML SDK fixed corrupted files like Microsoft Office (which does not work in all cases), I don't think it should be considered a bug if it doesn't do that.

**Comment by twsouthwick** [comment]
After rereading, I agree with @ThomasBarnekow. The SDK does not try to fix corrupted files and is out of scope of the project at the moment. It would be a nice feature, but would require a lot of work, when a simple work around would be to open in Office, repair, and then open with the SDK.

@Umeshpatil0012 if this is not the case, please feel free to reopen the issue and provide more details.
