### ISSUE TITLE
DocumentFormat.OpenXml.Office2013.WebExtension has typo in `Frozen` property

### ISSUE THREAD

**Issue by daniel-white** [OfficeDev/Open-XML-SDK#458]
**Description**

`DocumentFormat.OpenXml.Office2013.WebExtension` has a property named `Fronzen` which maps to `frozen` in the schema.

**Information**

- .NET Target: Any
- DocumentFormat.OpenXml Version: 2.8.1

**Observed**

`DocumentFormat.OpenXml.Office2013.WebExtension` has a property named `Fronzen` which maps to `frozen` in the schema.

**Expected**

I would expect a `Frozen` property, and perhaps the `Fronzen` one deprecated.

**Comment by tomjebo** [comment]
@daniel-white thanks for pointing this out. This is a generated property and the code is on our backend processing project. I'll take a look and get this corrected.

**Comment by tomjebo** [comment]
I found the backend schema code that has this and it looks to me that 1) it's just a typo and 2) it's been there since very long ago, probably predating this repo. 

This will constitute a breaking change because this is an attribute of the webextension element (complex type CT_OsfWebExtension) and wrapped by the WebExtension class. We will have to rebuild the generated classes and then update the sdk in a major version. It's fairly cosmetic but should be changed to match the true attribute name. 
This will have to go into our vnext list. In the meantime, I think it's safe to leave Fronzen as it's not actually broken just not named appropriately.

@daniel-white (& @twsouthwick) Do you agree?

**Comment by tomjebo** [comment]
I added this to [v3.0 project card 1](https://github.com/OfficeDev/Open-XML-SDK/projects/1)

**Comment by twsouthwick** [comment]
This sounds good to me. It'll definitely be a breaking change, but an easy change to make for v3.0. There are a number of spelling errors on other properties that we should try to fix. @daniel-white, I'm going to expand this issue to track spelling issues that need to be fixed

**Comment by twsouthwick** [comment]
Actually, I think @daniel-white has a good suggestion where we can add the correct property, and obsolete the old one. One of the things we'll do for v3.0 is to remove all obsolete items in the code base.

**Comment by twsouthwick** [comment]
I've submitted a PR that has the fix without causing a breaking change. We should audit the current member list to see other typos - I've seen them sporadically, but until recently, hadn't known an easy way to fix it with the schema generator.
