### ISSUE TITLE
Create an abstracted package exporter/importer

### ISSUE THREAD

**Issue by twsouthwick** [OfficeDev/Open-XML-SDK#479]
Currently, there is some functionality to export/import packages to/from strings via the `ToFlatOpc…` helpers. However, it would be nice to separate this out and create a generalized export/import pattern. This issue is to track this for vNext and to gather ideas of what we could/should include in this design.

**Comment by ThomasBarnekow** [comment]
@twsouthwick Do you have a specific use case for this? 

For example, I contributed the Flat OPC helpers to deal with Flat OPC strings produced by the Word API and to transform documents using XSLT transformations. An interesting question would be whether it made sense for the Office team to produce and consume (complete) `WordprocessingDocument` instances directly, for example, rather than Flat OPC strings.

**Comment by twsouthwick** [comment]
This came up in a discussion in #478 and the idea is to separate out any exporters/importers to a simplified pattern. This does a couple of things:

- Keeps a separation of concerns of the data and any supported file formats. It doesn't make sense to extend and have the package know about each format that it may be saved to.
- Could provide an interface for importing/exporting that would make it easy to change the format input and output types

Is Flat OPC a format Word supports natively?

**Comment by ThomasBarnekow** [comment]
At least since Word 2010, there is the [`Range.WordOpenXML` Property](https://msdn.microsoft.com/en-us/library/microsoft.office.interop.word.range.wordopenxml(v=office.14).aspx).

I believe Excel and PowerPoint don't have similar capabilities.

**Comment by daniel-white** [comment]
In officejs, its the way to insert xml in - can't just provide it a snip either. In Word there is a save as XML option which generates it.
