### ISSUE TITLE
Using the Open XML SDK to manipulate Wrod how do I move the cursor to a particular paragraph

### ISSUE THREAD

**Issue by xiangxingze** [OfficeDev/Open-XML-SDK#520]
Please help me, when using the Open XML SDK to generate a Word document through the Word template in the.net core platform, how do I move the cursor to a specific paragraph?

中文：在.net core 平台下使用Open XML SDK 通过Word模板生成Word文档时，如何将光标移动到特定的段落？

**Comment by ThomasBarnekow** [comment]
@xiangxingze This is a typical stackoverflow.com question rather than an issue with the Open XML SDK. However, as it is a quick answer, the following example shows the markup that you want to create:
```xml
    <w:p>
      <w:r>
        <w:t>Hello World!</w:t>
      </w:r>
      <w:bookmarkStart w:id="0" w:name="_GoBack"/>
      <w:bookmarkEnd w:id="0"/>
    </w:p>
```
Word uses a special bookmark called "_GoBack" to mark the paragraph that was last edited. However, it seems that it Word does not (always) go there but rather just offers the user the option to go where they left off.

**Comment by twsouthwick** [comment]
As @ThomasBarnekow said, this is not related to the SDK functionality directly, but rather usage of the schema. Thanks for answering! I'm going to close this issue, @xiangxingze , but feel free to open again if you find issues with the SDK.
