### ISSUE TITLE
How to build the open xml?

### ISSUE THREAD

**Issue by fmoghaddampoor** [OfficeDev/Open-XML-SDK#522]
Hi
For one of my projects I want to embedd the open xml into one of my dlls . I started downloading master Open xml from below address: https://github.com/OfficeDev/Open-XML-SDK And tried to build it first, but to my dismay its saying The SDK 'Microsoft.NET.Sdk' specified could not be found

I have looked at below address and I saw I have installed these .net cores: C:\Program Files\dotnet\sdk

1.0.0, 1.1.9, 1.1.10, 2.0.2, 2.1.2, 2.1.201, 2.1.202, 2.1.400, 2.1.401

In the cs project its written netstandard1.3 is needed. But I can not find this package on microsoft website.

Do you know how I can build OpenXml?

**Comment by tomjebo** [comment]
@fmoghaddampoor could you take a look at this post [error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.](https://github.com/Microsoft/msbuild/issues/2532)? Specifically, you may need to add a workload to your VS setup: .Net Core Build Tools. 

Tom

**Comment by tomjebo** [comment]
@fmoghaddampoor let us know if you still have a problem here. To answer your question about .Net Standard 1.3, there is no package. .Net Core 1.0.0 supports .Net Standard 1.3 so if you have .Net Core installed then you should be good to go. You can read more here: [.Net Standard specification](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)

**Comment by fmoghaddampoor** [comment]
One of the problems with nuget format mode is there are super many files generated as output in Bin folder which makes nuget mode useless as we just need one dll for our clients. And the only thing We need from openxml is to change xlsx revision file properties.

**Comment by tomjebo** [comment]
@fmoghaddampoor is it building successfully aside from the extra unwanted files? Are you just trying to remove dependencies?

**Comment by fmoghaddampoor** [comment]
The Nuget format mode is working with two extra files:
DocumentFormat.OpenXml.dll
DocumentFormat.OpenXml.xml

However to my dismay sometimes a lot of system.* files also go to bin which I remove them and it works.
For the part of building master Im not sucessful still:

MSB4044	The "GetAssemblyVersion" task was not given a value for the required parameter "NuGetVersion". DocumentFormat.OpenXml.Benchmarks

MSB4044	The "GenerateDepsFile" task was not given a value for the required parameter

**Comment by fmoghaddampoor** [comment]
As I have tried to go your way I have first tried to find the build tools however visual studio installer did not have the item. So I totally removed visual studio and then I reinstall it again and this time I find the build tools. I could at the end build the project with no error however the c# used is super high 7.2 🙄which needs also. Net framework 4.7. Also to my dismay I found it uses a system.io.packaging. Which I may need time to get that from core fx and try to embedd it. Your solution is true, but visual studio installer did not have that option at first so I totally reinstalled my VS. Thanks

**Comment by twsouthwick** [comment]
Hi @fmoghaddampoor I think we should take a step back to understand what your ask actually is. Sounds like you want to embed the SDK in another assembly. Can you please help us understand what your scenario is (ie why do you want to do this)? The recommended way to go about this is to create a NuGet package that then takes a dependency on this package. The benefit of it is:

- You are not responsible for the servicing of the SDK you ship
- Our releases are Authenticode signed so people understand where it comes from and the code can't be altered after it's released (the OS won't load it)
- Works with how the JIT (or AOT compilers) expect assemblies to be packaged

Embedding has a number of meanings and a few possible implementations. Sounds like you are trying to build it yourself into some other project. You are free to do so, but we probably won't be able to help you too much as that is not a goal of this project. The build system is non-trivial and is designed to produce a NuGet package with assemblies targeting specific frameworks.

You mentioned C# 7.2 (we'll probably bump it to 7.3 soon to take advantage of some new features). You do not need .NET Framework 4.7 to use this, at least as long as you don't have public surface with new ref/etc features. There is no easy way to not use 7.2 as those features are pervasive in the project. If you consume the SDK as an assembly, the language choice will not affect you.

Your concern of System.IO.Packaging is due to the way packages work in the .NET Standard world. There is another package that is required as well (I can't remember off the top of my head). Again, this would be solved by just using the NuGet package.

There are a couple of tooling options to "embed" an assembly, including ILMerge and ILLinker. I'm not endorsing either one and you'll be on your own to get them to work. Depending on what you are building, this may or may not work.

With all that said, can you please describe your scenario as I'm betting there's a better solution than trying to embed the SDK in the way you are attempting.

**Comment by twsouthwick** [comment]
For directions on building, see https://github.com/OfficeDev/Open-XML-SDK/blob/master/README.md#to-build-the-open-xml-sdk. This is only if you stay on the "golden path" - as I said, the build process is non-trivial

**Comment by twsouthwick** [comment]
@fmoghaddampoor Any updates?

**Comment by fmoghaddampoor** [comment]
Well actually the problem is we have a synchronizing system which we are releasing all the time our files for lots of clients, so the they start using the dlls in one system from many app at the same time. And if they are in use synchronization can not be done until all the processes shut down on client computer. We have find the solution by renaming dlls in use and copy new dll. but what will happen if I have open xml running in assemblies and one app is accessing this dlls and I copy new dll of yours to client.

**Comment by tomjebo** [comment]
Would it be more appropriate to build an isolated application? [Isolated Applications](https://docs.microsoft.com/en-us/windows/desktop/sbscs/isolated-applications)
This would allow you to select which assemblies and DLLs you use and where they come from.

**Comment by twsouthwick** [comment]
This sounds like you need to figure out a better deployment strategy. What kind of application is this? Client or server? I'm assuming client. How are you deploying? Using click-once/appx/msix/installers should be able to handle this transparently for you.

**Comment by twsouthwick** [comment]
As I said, you're deployment strategy is the issue here. Why do you not put everything in a specific directory for each application that needs it? Are these loaded as extensions in the applications? Are you automating this under a client w/o their knowledge or are they opting into it?

**Comment by twsouthwick** [comment]
Also, what do you mean by this:

> the user may start synchronizing in cad

**Comment by fmoghaddampoor** [comment]
Well users start synchronizing from cad to get new software and new database, lets say a button which synchronize the software which may already be used in another instance of cad. so a cad runs a vb script , vbscript is using a com exposed function of c#, which is a  dll which uses your dll. the software is doing long running batch process. then another app is synchronizing the files already in use even vbscript or also your dll, but process of the other cad must never and never fail as it would be huge damage.

**Comment by twsouthwick** [comment]
Ok - I understand what you're doing. Is this run in the same process? If so, you'll need to unload the assemblies so you can correctly reload things. However, most applications require a restart for this precisely so they don't run into issues you are describing (ie Visual Studio does that with their extensions).

Since this is not something SDK, I'm going to close this issue. Good luck with your scenario and let us know if you hit issues with the SDK itself.

**Comment by twsouthwick** [comment]
@fmoghaddampoor btw Stackoverflow is usually a good place for this kind of question. If you submit the question there, paste the link here so we can potentially help there.
