### ISSUE TITLE
search and replace text

### ISSUE THREAD

**Issue by dkddkk** [OfficeDev/Open-XML-SDK#529]
using (WordprocessingDocument xxDoc = WordprocessingDocument.Create(dstPath, WordprocessingDocumentType.Document))
{
MainDocumentPart objMainDocumentPart = xxDoc.AddMainDocumentPart();
objMainDocumentPart.Document = new Document(new Body());

           //add paragraphs here
           //Open-Xml-PowerTools
           TextReplacer.SearchAndReplace(xxDoc, tTarget, tKeyVP.Value, true);
}

SearchAndReplace will throw an exception. _exceptionMethod = {System.Xml.Linq.XDocument GetXDocument(DocumentFormat.OpenXml.Packaging.OpenXmlPart)}

It should be xxDoc cannot build the OpenXmlPart, what should I do? Please give me a method.

ps:
for example:
var inputDoc = WordprocessingDocument.Create("ttt.docx", WordprocessingDocumentType.Document);

        MainDocumentPart inputMainPart = inputDoc.AddMainDocumentPart();
        inputMainPart.Document = new Document(new Body(new 
       DocumentFormat.OpenXml.Wordprocessing.Paragraph(new Run(new Text("Hello,world."))), new                       DocumentFormat.OpenXml.Wordprocessing.Paragraph(new Run(new Text("xxxx.")))));
        inputDoc.Save();

        TextReplacer.SearchAndReplace(inputDoc, "xxx", "ccc", false);
I got a null exception, whenever I save it then open the doc or I create it in memory like above.

Please tell me what should I do?

The word is here:

<?xml version="1.0" encoding="utf-8"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:r><w:t>Hello,world.</w:t></w:r></w:p><w:p><w:r><w:t>xxxx.</w:t></w:r></w:p></w:body></w:document>

**Comment by ThomasBarnekow** [comment]
Your question or issue is not related to the Open XML SDK but rather the PowerTools for Open XML. The GetXDocument Extension method and the static TextReplacer class are not part of the SDK.

All of this is Open Source, so you can debug and see what the problem is. You should also have a look at the articles written by Eric White, e.g., on the TextReplacer. However, you might want to consider the OpenXmlRegex class as well.
