### ISSUE TITLE
Wordprocessing.PermStart.Id field illegal type

### ISSUE THREAD

**Issue by Ingerdev** [OfficeDev/Open-XML-SDK#581]
DocumentFormat.OpenXml.Wordprocessing.PermStart.Id field has Int32 type instead of string type
as Ecma standart says. Please fix it.

**Comment by Ingerdev** [comment]
DocumentFormat.OpenXml.Wordprocessing.PermEnd.Id should be fixed too.

**Comment by twsouthwick** [comment]
Thanks, @Ingerdev. Schema related issues are a bit tricky to change (and this would be a breaking change to introduce). Are you hitting an issue due to this or is it so it aligns with the standard? This will help us identify the severity.

**Comment by Ingerdev** [comment]
This type of error is nasty, however, I have a workaround for it so nothing hurry.
(Imagine valid xml where id is a guid. OOXML library cant restore its value on load)

**Comment by twsouthwick** [comment]
Yes, I can definitely see the potential issue. Have you seen a document that has a guid or other invalid integer as the id? If Word, for instance, is creating GUIDs as the Id, the impetus to fix this has just grown.

A v3.0 is becoming more likely as breaking changes are required for a few things, so we can add this to the list.

**Comment by Ingerdev** [comment]
No, i never saw such a document.

**Comment by tomjebo** [comment]
Although the standard (ISO 29500-1 17.13.7 Range Permissions and Annex A (normative) Schemas... CT_Perm) state that id is of type ST_String, the SDK is based on Office specific behavior. This behavior is described in:

[[MS-OI29500]: Office Implementation Information for ISO/IEC 29500 Standards Support](https://docs.microsoft.com/en-us/openspecs/office_standards/ms-oi29500/1fd4a662-8623-49c0-82f0-18fa91b413b8)

In 2.1.357 of that document, we state: 

> c. The standard states that the value of the 'id' attribute can be any string.
>     Word allows only 32-bit integers for the id attribute.

Therefore, the code here is by design.

**Comment by Ingerdev** [comment]
Thanks, it is pretty informative.
