### ISSUE TITLE
Add snk file to System.IO.Packaging,DocumentFormat.OpenXml and PowerTools .Strong-name signed assemblies must specify a public key in their InternalsVisibleTo declarations.

### ISSUE THREAD

**Issue by Ganesan-Chandran** [OfficeDev/Open-XML-SDK#60]
Hi,

I have add latest OpenXml SDK (2.6) and PowerTools 4.0 in my project.I have added snk file to my project.I got Unable to emit assembly error.So i try to add snk file for System.IO.Packaging,DocumentFormat.OpenXml and PowerTools . For System.IO.Packaging there is no problem.But For DocumentFormat.OpenXml,After adding snk file i got below error.

Friend assembly reference 'SdbBuilder' is invalid. Strong-name signed assemblies must specify a public key in their InternalsVisibleTo declarations.

Friend assembly reference 'ofapiTest' is invalid. Strong-name signed assemblies must specify a public key in their InternalsVisibleTo declarations.

File name is (ofapi.cs)

How to solve above error.

How to add snk file to all 3 projects.I need dll with stong named type project.
Please help me to resolve the issue.

**Comment by EricWhiteDev** [comment]
I'm open to incorporating this if anyone is free to do the work.  Can propose a plan of action, with proposed files to be added to the repo, and can discuss.

**Comment by k59319** [comment]
I have exactly the same issue building OpenXml SDK 2.6. There are no binaries Microsoft.com website, no nuget package, and it's impossible to build it straight from the sources. Do you have any updates on this issue?

**Comment by gabisandor** [comment]
@Ganesan-Chandran : you have to modify the InternalsVisibleTo declarations so that they contain the public key besides the assembly name, it worked for me.

However, i was not successful in the end, even after i sign all assemblies many of the unit tests fail due to some deserialization problems involving .bin files in src\GeneratedCode. I have honestly no idea how to solve this properly.

Another alternative would be to have the Open XML SDK binaries signed and published via NuGet, there is already an open discussion about this: https://github.com/OfficeDev/Open-XML-SDK/issues/2.

Anyway, it's probably not a very good idea to include a private key (.snk) file here in GitHub, that would mean disclosing an author's and/or Microsoft's private key, which is one of the worst kind of failure you can make in terms of security and digital signatures...

**Comment by akoeplinger** [comment]
> Anyway, it's probably not a very good idea to include a private key (.snk) file here in GitHub, that would mean disclosing an author's and/or Microsoft's private key, which is one of the worst kinds of failure you can make in terms of security and digital signatures...

@gabisandor Strong Name signing is not a security feature. See https://msdn.microsoft.com/en-us/library/wd40t7ad(v=vs.110).aspx:
> Do not rely on strong names for security. They provide a unique identity only.
> [..]
> If you are an open-source developer and you want the identity benefits of a strong-named assembly, consider checking in the private key associated with an assembly into your source control system.

**Comment by gabisandor** [comment]
@akoeplinger: Hmm, i'm confused about this. What's stopping then someone from getting the private key which is now available to everyone, use it to sign his own assembly name DocumentFormat.OpenXml and impersonate maliciously this official assembly?

**Comment by akoeplinger** [comment]
@gabisandor nothing, that's the point. If you want security, you need to Authenticode sign the assembly. Strong Names are not the right tool for that.

**Comment by gabisandor** [comment]
@akoeplinger: So it seems i mixed these 2 distinct concepts all this time :). Thanks for pointing this out!

**Comment by akoeplinger** [comment]
@gabisandor don't worry, it's a *very* common misconception :)

**Comment by tomjebo** [comment]
Closing as we now have strong naming in the current builds.
