### ISSUE TITLE
The thread-safe issue regarding IsolatedStorage

### ISSUE THREAD

**Issue by nihao0818** [OfficeDev/Open-XML-SDK#616]
Is this a:
- [x] Issue with the OpenXml library
- [x] Question on library usage

**Description**

It was known to us that OpenXMLSDK had an implementation to use IsolatedStorage for PartPackage larger than 10MB which was not thread-safe. 

Details:
https://social.msdn.microsoft.com/Forums/office/en-US/fcccab24-cd48-40fc-afbb-a7c30191a9e1/open-xml-sdk-v2-handling-multiple-threads
https://stackoverflow.com/questions/21482820/openxml-hanging-while-writing-elements

I’m wondering if that implementation has been changed since then. And if not, do you have any recommendation to handle it in a multi-thread environment? 

**Information**

- .NET Target:  .NET Framework 4.6.2
- DocumentFormat.OpenXml Version: latest

**Comment by KalleOlaviNiemitalo** [comment]
See [WindowsBase or System.IO.Packaging](https://github.com/OfficeDev/Open-XML-SDK/blob/master/README.md#windowsbase-or-systemiopackaging) in README.md.

The MSDN forum thread at your first link has a comment saying that the bug in System.IO.Packaging of .NET Framework was fixed in [KB2996568](https://support.microsoft.com/en-us/help/2996568/hotfix-rollup-2996568-for-the-net-framework-4-5-4-5-1-and-4-5-2-on-vis "Hotfix rollup 2996568 for the .NET Framework 4.5, 4.5.1, and 4.5.2 on Vista SP2, Windows Server 2008 SP2, Windows 7 SP1, and Windows Server 2008 R2 SP1"). I assume .NET Framework 4.6 inherited that fix.

**Comment by twsouthwick** [comment]
@nihao0818 This seems to be fixed in later versions of .NET Framework. If you have a repro, please let us know but according to KB2996568, it has been fixed. Thanks @KalleOlaviNiemitalo for the link. I'm closing this, but please reopen if you can repro it on a recent .NET Framework version (or any other version).
