### ISSUE TITLE
Repeated Header and footer count

### ISSUE THREAD

**Issue by rajcitystar** [OfficeDev/Open-XML-SDK#62]
Acutally i need to get the characters count in docx(including header and footer).
but open xml sdk is not giving header and footer part count.
now i have read the header and footer text. but I would like to know the number of time the header and footer text used in docx. so that i can multiply and get the correct count of header and footer text

**Comment by EricWhiteDev** [comment]
@rajcitystar The Open XML SDK does not have this feature.  In order to get this information, first we would have to paginate the document, so that we would know what the pages are for the document.  We could then, in theory, figure out which headers / footers are used.  However, there is no functionality in the Open-Xml-Sdk to figure out pagination, so this functionality is not possible.  We don't contemplate adding pagination functionality to the SDK, so I am closing this issue.  We can't fix this issue with the Open XML SDK.
