### ISSUE TITLE
PPTX Sunburst chart?

### ISSUE THREAD

**Issue by mooop12** [OfficeDev/Open-XML-SDK#674]
How would I go about creating a sunburst chart using OpenXML SDK? I tried reflecting it using the Productivity Tool but it would seem it does not support it correctly, and the chart itself is an image embedded into the PPTX. Seems to be stored very much differently than other types of charts.

I know this is a question and not a bug, but SO is entirely unhelpful in answering new questions, I tried asking and they just outright closed my question.

**Comment by tomjebo** [comment]
@mooop12 Charts are more complex to create and this is indeed a "how to" question. I'm not sure what might be going on with the reflection code, if I have some time, I might try the same exercise. However, in the meantime you might want to look at this post on StackOverflow: 
[How to create chart/graph in excel sheet OpenXML 2.0 C#](https://stackoverflow.com/questions/11365430/how-to-create-chart-graph-in-excel-sheet-openxml-2-0-c-sharp)

**Comment by mooop12** [comment]
We actually have (other) chart creation pretty much covered, it's just that Sunburst seems to be a new chart in Office 2016 and there aren't any Sunburst classes in Open XML SDK currently. From what I've seen, Office 2016 initial support has just been added to the SDK in version 2.10.

**Comment by tomjebo** [comment]
The classes are actually generated but I think the problem here is that the productivity tool just doesn't know about them and I don't happen to have an example of generating a chart like that. Two options here come to mind, 1) manually come up with the code based on the classes. The chartex code works a little differently than for example doing a BarChart but it should be possible, although tedious, to write this by hand. 2) update the Productivity Tool to pull in the latest SDK so it can properly reflect based on a PowerPoint genned example. 
The classes in the schemas_microsoft_com_office_drawing_2014_chart.g.cs, ...chart_ac.g.cs, and ...chartex.g.cs generated classes. Following the schemas, you'll need to create a Chart instance, with a PlotArea, that has a PlotAreaRegion, that has a Series with a LayoutId property set to the Sunburst enum for SeriesLayout, in order to get a Sunburst layout. I.e. there's not a Sunburst class like the BarChart class. The relationship to the chart part will have to be `Type="http://schemas.microsoft.com/office/2014/relationships/chartEx"` which means using the ExtendedChartPart class in the Packaging generated code. There will be more and it will be some work.

**Comment by ThomasBarnekow** [comment]
@tomjebo, isn't the productivity tool based on a pretty old version of the Open XML SDK? Does this ever get updated?

**Comment by tomjebo** [comment]
@ThomasBarnekow it's based on 2.5 (pre-github) and hasn't been updated AFAICT.  I'll spend some time manually putting together the sunburst example and see if there are any issues with it.

**Comment by twsouthwick** [comment]
This is being tracked by #675

**Comment by tomjebo** [comment]
@mooop12 just to follow up on this since it's been a while. we merged PR #687 that addressed this issue. #675 was also dealing with this but I wanted to circle back here in case you are not tracking that issue. chartSpace is now added and the support for Sunburst chart types (as well as several other 2016 types) is in place. we've also added a project in the samples folder to demonstrate how a Sunburst chart could be generated. Please file a new issue if you find that something is not working correctly with these chart types.
