### ISSUE TITLE
Validator does not verify CellValue contents match content type

### ISSUE THREAD

**Issue by MoamenMohamed93** [OfficeDev/Open-XML-SDK#697]
Is this a:
- [X] Issue with the OpenXml library

**Description**

Invalid Excel document that shows error message "We found a problems with some content...." while opening using Microsoft Excel 2019 is reported as valid by Open XML SDK Validator.

**Information**

- .NET Target: .NET Core 3.1
- DocumentFormat.OpenXml Version:  (2.10.1)

**Repro**

Create a Cell with string value and data type set to **Number**. 
Validate the created excel using OpenXmlValidator return no errors.

**Expected**

The validation results contain errors.

**Comment by tomjebo** [comment]
@MoamenMohamed93 can you please share repro code for this problem? It is possible to create OpenXML packages that are not accepted by Word, PowerPoint and Excel but which look "valid".  Please share the code.

**Comment by MoamenMohamed93** [comment]
@tomjebo  Here you are https://github.com/MoamenMohamed93/ExcelValidationTest
Yes it looks as a valid xml, Is there any way I can check if a package is valid?

**Comment by tomjebo** [comment]
@MoamenMohamed93 I think the problem is just that the code you're using is setting the cell value DataType to "Number" when the content is a string. I changed it to this: 

`                sheetData.AppendChild(new Row(new Cell()
                {
                    CellValue = new CellValue("StringValue"),
                    DataType = CellValues.String
                }));
`

And this works just fine. 
As far as validation, I don't think we check for this as it would require checking the content (CellValue) and represents more of a semantic validation.

**Comment by MoamenMohamed93** [comment]
> As far as validation, I don't think we check for this as it would require checking the content (CellValue) and represents more of a semantic validation.

@tomjebo And there is no way to do the same semantic validation like what excel does?

**Comment by tomjebo** [comment]
@MoamenMohamed93 we could add this as a feature request. But I believe validation is schema validation in the current code. If there is semantic or other validation in our code (and there might be) it's likely added ad-hoc.

**Comment by twsouthwick** [comment]
There is semantic validation, and I've done a bunch of work to make it easier to extend. We can potentially add this. We'll keep it as enhancement. I won't have time to address this for a while, but @MoamenMohamed93  if you want to take a look, feel free :)

**Comment by rmboggs** [comment]
A little late to this party but my 2 cents on this issue if anyone is interested:

There seems to be a disconnect with validation between the SDK and Microsoft Office ever since 2.0 of the SDK.  I've seen documents that passed sdk validation that Microsoft Office would not even open and documents that MS Office wouldn't have problems with that the SDK would have multiple failures on.  I always assumed the reasoning for this is because these items are checking two different topics, the SDK checking the XML content against the openxml sdk documented schema and MS Office checking for invalid file settings.  A prime example of this would be a worksheet row object (row 1) containing 5 cell objects with the cell reference all set to "A1".  I've seen this scenario where the document passed the open xml sdk validator but Excel wanted nothing to do with the file, for obvious reasons.  

It would be nice to check for the things that MS Office checks for when opening documents but I fear that would be very difficult to accomplish.  However, I do feel that there is an opportunity to check for simple items, like an invalid cell data type and duplicate cell references within a row element. And if my assumption above is correct regarding the SDK validator, then this sort of check would be a new testing class within this project or a separate project altogether.

**Comment by twsouthwick** [comment]
Yes, this is something that we could add and makes sense. Let's have this issue track cell value types. Feel free to open issues for other things the validator should handle.

**Comment by twsouthwick** [comment]
If anyone is interested, here is a potential way to handle it (purely POC haven't actually tried it).

1. First would be to add a method to OpenXmlElement:

```csharp
public class OpenXmlElement
{
  internal virtual void Validate(ValidationContext context)
  {
  }
}
```

2. Add a call to that in the validator around here:

https://github.com/OfficeDev/Open-XML-SDK/blob/3cb921efb711169c259f756171959d1281fb98dc/src/DocumentFormat.OpenXml/Validation/Schema/SchemaTypeValidator.cs#L45-L50

```csharp
theElement.Validate(validationContext);
```

3. Implement logic for the `CellValue` type to check for correct states.

Not sure if that's the best way to do it, but should point anyone interested in exploring that in the right direction.

**Comment by twsouthwick** [comment]
Added in #782
