### ISSUE TITLE
Receive exception when accessing SharedStringTablePart from multiple threads simultaneously

### ISSUE THREAD

**Issue by rjmille2msft** [OfficeDev/Open-XML-SDK#70]
I get this exception even when I open the file using read only attributes.  So why couldn't multiple threads that have a read only view of the file open be able to read the SharedStringTable Part?

```
// Open System.IO.Packaging.Package.
            Package spreadsheetPackage = Package.Open(in_ss, FileMode.Open, FileAccess.Read);

            // Open a SpreadsheetDocument based on a package.
            SpreadsheetDocument document = SpreadsheetDocument.Open(spreadsheetPackage);
            workbookPart = document.WorkbookPart;

            SharedStringTablePart shareStringPart = null;
            if (workbookPart.GetPartsCountOfType<SharedStringTablePart>() > 0)
            {
                shareStringPart = workbookPart.GetPartsOfType<SharedStringTablePart>().FirstOrDefault();
            }

text = shareStringPart.SharedStringTable.ElementAt(
                            Convert.ToInt32(cell.CellValue.Text)).InnerText;
```

System.IO.InvalidDataException was unhandled by user code
  HResult=-2146233087
  Message=A local file header is corrupt.
  Source=System.IO.Compression
  StackTrace:
       at System.IO.Compression.ZipArchiveEntry.ThrowIfNotOpenable(Boolean needToUncompress, Boolean needToLoadIntoMemory)
       at System.IO.Compression.ZipArchiveEntry.OpenInReadMode(Boolean checkOpenable)
       at System.IO.Compression.ZipArchiveEntry.Open()
       at System.IO.Packaging.ZipStreamManager.Open(ZipArchiveEntry zipArchiveEntry, FileMode streamFileMode, FileAccess streamFileAccess)
       at System.IO.Packaging.ZipPackagePart.GetStreamCore(FileMode streamFileMode, FileAccess streamFileAccess)
       at System.IO.Packaging.PackagePart.GetStream(FileMode mode, FileAccess access)
       at DocumentFormat.OpenXml.Packaging.OpenXmlPart.GetStream(FileMode mode, FileAccess access)
       at DocumentFormat.OpenXml.Packaging.OpenXmlPart.LoadDomTree[T]()
       at DocumentFormat.OpenXml.Packaging.SharedStringTablePart.get_SharedStringTable()
       at SRPPEVL.Program.ReadExcelCell(Cell cell, SharedStringTablePart shareStringPart) in c:\users\ramiller\documents\visual studio 2015\Projects\SRPPEVL\SRPPEVL\Program.cs:line 117

**Comment by EricWhiteDev** [comment]
@rjmille2msft Unfortunately, we know that the Open XML SDK is not thread safe.  Making it be thread-safe would entail going through the code with a fine-toothed comb, identifying and fixing some known static state.  Further, it would entail identifying the key scenarios, and writing XUnit tests that exercise the functionality in those scenarios, and fixing the SDK as appropriate.  This task is not currently scheduled, nor is it anticipated to be in the near future.

If you need to get high performance on multi-core machines, I recommend starting multiple executables, each with their own workload.

I'll leave this issue open, but would not expect it to be addressed in the near future.

**Comment by rjmille2msft** [comment]
I could understand this being an issue if I had the document open for read/write, but when it is opened read-only shouldn't it be somewhat easier to implement the multi-threading?

Randy

Sent from my Windows Phone
________________________________

**Comment by KLuuKer** [comment]
@EricWhiteDev you just said something really scary 
> I recommend starting multiple executables, each with their own workload.

i hope you meant instances of a SpreadsheetDocument
can we get a confirmation that what you actually meant is the following? (and maybe update the readme file with this sentence)
> Public static (Shared in Visual Basic) members of this type are thread safe. Any instance members are not guaranteed to be thread safe. 

because we use then openxmlsdk for reading and writing excel sheets that our customers upload\download to our web application and multiple read's and write's to **different instances** can and will happen

**Comment by twsouthwick** [comment]
@rjmille2msft This has more to do with the underlying data structures not being thread safe. Many are lazily created and can cause race conditions. There are literally thousands of properties that fall into this category, so it would be a massive undertaking to update and test for thread safety.

@KLuuKer I'm not sure what @EricWhiteDev was referring to, but each package you open should only be accessed from the same thread (or synchronized appropriately). 

Since this is by-design at the moment, and no guarantee of thread safety is implied, I'm closing this issue.
