### ISSUE TITLE
Schema Error : The 'urn:schemas-microsoft-com:office:office:gfxdata' attribute is not declared.

### ISSUE THREAD

**Issue by 06needhamt** [OfficeDev/Open-XML-SDK#709]
Is this a:
- [X] Issue with the OpenXml library
- [ ] Question on library usage

**Description**

Schema Error : The 'urn:schemas-microsoft-com:office:office:gfxdata' attribute is not declared. On 2 separate valid Office 365 Word documents.

**Information**

- .NET Target: .NET 4.6.2
- DocumentFormat.OpenXml Version: 2.10.1

**Repro**

Validate the attached file with a WordDocumentValidator.

**Observed**

The following validation error was reported.

Schema Error : The 'urn:schemas-microsoft-com:office:office:gfxdata' attribute is not declared.

**Expected**

The file should have been validated successfully without errors.
[gfxdata.docx](https://github.com/OfficeDev/Open-XML-SDK/files/4383497/gfxdata.docx)

**Comment by tomjebo** [comment]
@06needhamt just double checking on this, how did you generate gfxdata.docx? According to ISO 29500-4:2016 19.1.2.16 "rect (Rectangle)", gfxdata is not an attribute of CT_Rect type. If this was generated with Word, can you give me repro steps with word to create the document?

**Comment by 06needhamt** [comment]
Hi @tomjebo the file in question was downloaded from [here](https://www.fhvzelm.com/files/LettertypenAlle.docx). 

Hope this helps you diagnose the problem. Let me know if you need any more info.

**Comment by tomjebo** [comment]
@06needhamt I found the reference. [MS-OI29500] has several references like this one for 19.1.2.13 oval (Oval)
which say: 
"The standard does not mention the gfxdata attribute.
Office uses an gfxdata attribute. The definition is the same as the gfxdata attribute defined in
Section 14.1.2.19."

This is for the transitional markup, specifically for vector ML (VML). Since these are not in the schemas and Office just accepts these as attributes of several additional elements (besides <shape>), we'll need to add these to the schema generation code. 

Thanks for bringing this to our attention.
