### ISSUE TITLE
Schema Error : The attribute 'anchory' has invalid value 'line'. The Enumeration constraint failed.

### ISSUE THREAD

**Issue by 06needhamt** [OfficeDev/Open-XML-SDK#736]
Is this a:
- [X] Issue with the OpenXml library
- [ ] Question on library usage

**Description**

Schema Error : The attribute 'anchory' has invalid value 'line'. The Enumeration constraint failed. On 2 separate valid Office 365 Word documents.

**Information**

- .NET Target: NET 4.6.2
- DocumentFormat.OpenXml Version: 2.11.0

**Repro**

``` charp
class Program
    {
        static void Main(string[] args)
        {
            OpenXmlPackage wordDocument1 = WordprocessingDocument.Open("BouwstenenAlle.docm", false);
            List<ValidationErrorInfo> errorInfos1 = ValidateDocument(wordDocument1);

            foreach (ValidationErrorInfo info in errorInfos1)
            {
                Console.WriteLine(string.Format("BouwstenenAlle.docm Error Occurred {0}", info.Description)); 
            }

            OpenXmlPackage wordDocument2 = WordprocessingDocument.Open("LettertypenAlle.docx", false);
            List<ValidationErrorInfo> errorInfos2 = ValidateDocument(wordDocument2);

            foreach (ValidationErrorInfo info in errorInfos2)
            {
                Console.WriteLine(string.Format("LettertypenAlle.docx Validaton Error Occurred {0}", info.Description));
            }

            Console.ReadKey();
        }

        static List<ValidationErrorInfo> ValidateDocument(OpenXmlPackage package)
        {
            OpenXmlValidator validator = new OpenXmlValidator(FileFormatVersions.Office2016);
            List<ValidationErrorInfo> validationErrors = validator.Validate(package).ToList();

            return validationErrors;
        }
    }
```

**Observed**

The following validation error was reported on both files.

Schema Error : The attribute 'anchory' has invalid value 'line'. The Enumeration constraint failed. 

**Expected**

Both files should have been validated successfully without the above error.

[InvalidFiles2.zip](https://github.com/OfficeDev/Open-XML-SDK/files/4730388/InvalidFiles2.zip)

**Comment by 06needhamt** [comment]
Is there any ETA on a fix for this issue?

**Comment by twsouthwick** [comment]
Looks like an enumeration value is missing here:

https://github.com/OfficeDev/Open-XML-SDK/blob/3cb921efb711169c259f756171959d1281fb98dc/src/DocumentFormat.OpenXml/GeneratedCode/schemas-microsoft-com_office_word.g.cs#L523-L546

@tomjebo Any thoughts on that? Seems like some of the previous issues we had

**Comment by 06needhamt** [comment]
@twsouthwick I have added a complete repro to the main comment, hopefully this will assist you further

**Comment by twsouthwick** [comment]
@06needhamt Thanks. The issue is that apparently there is supposed to be a `line` value in the enumeration. We fixed a few missing enum values last release, so I'm thinking it's a similar thing for this one.

**Comment by 06needhamt** [comment]
@twsouthwick Great. Are there any time lines set for that release yet.

**Comment by twsouthwick** [comment]
At this time no time is set. However, a number of API updates are on the docket, so probably within a month

**Comment by twsouthwick** [comment]
@tomjebo

**Comment by 06needhamt** [comment]
@twsouthwick @tomjebo, Is there any update on this issue yet. This issue seems to be getting more common on our end.

**Comment by twsouthwick** [comment]
Yes, @tomjebo is looking into it. Should be a part of the next minor release.

**Comment by 06needhamt** [comment]
@twsouthwick @tomjebo Thanks. Any timelines for the next release containing this fix?

**Comment by tomjebo** [comment]
@06needhamt I apologize for delay in getting back to this. My review of this has revealed that this "Line" enum is not a Microsoft Office enum value but is just being accepted by way of ignoring it. Our implementation notes on the standard say this: 

_Word ignores the tblpPr element if all attributes are omitted. It also ignores this element if the table
is contained in a textbox, footnote, endnote, or comment, or if all of the following conditions are met:
 The tblpX attribute value is 0.
 The tblpY attribute value is 0.
 The horzAnchor attribute value is text.
 The vertAnchor attribute value is not text._

I took a look at example files in your original post and I didn't see ="line" anywhere. Can you identify the part and element it's being used in?

What would probably make more sense to do is add the above rules to the validation routines so that it matches the implementation note behavior.

**Comment by 06needhamt** [comment]
Hi @tomjebo Thank you for the response. I did a quick search over the two files that I attached and I found the below usages.

```xml
LettertypenAlle footer2.xml: <w10:wrap type="square" anchorx="margin" anchory="line"/>
BouwstenenAlle document.xml: <w10:wrap type="square" anchorx="margin" anchory="line"/>
BouwstenenAlle footer4.xml: <w10:wrap anchorx="margin" anchory="line"/> 
```

Hope; this helps you resolve the problem

**Comment by tomjebo** [comment]
@06needhamt Thanks for pointing to the markup. I figured out that the wrap element being used is in the VML transitional markup described in part 4 of ISO 29500. This is covered in our SDK and wrapped properly for Office. We have an implementation note in MS-OI29500 that states that this "line" enum is not valid for Office so the SDK is correctly calling this out. (see below link). Office will process it because in the documents you provided there's an alternate content block giving Office the chance to use markup it can process. The Fallback block (at least in two of them) is where the VML is used with the "line" enum. 

[2.1.1849 Part 4 Section 19.3.3.4, ST_VerticalAnchor (Vertical Anchor Type)](https://docs.microsoft.com/en-us/openspecs/office_standards/ms-oi29500/45d9c9bc-0827-46b1-9de0-553bf9a0fe56)

**Comment by tomjebo** [comment]
@06needhamt @twsouthwick I should add here that the question of providing strict and transitional ISO 29500 support in the SDK, particularly when it conflicts with Office behavior is something we've been considering but will likely be a separate project or require some special mechanism both on the back end and in the framework. Possible approaches could see side by side validation of 2007, 2010, 2013, 2016 and ISO. Perhaps even ISO:2008, ISO:2012, etc... Please feel free to comment with your thoughts. 
For now, one option for consumers of the SDK, is to fork and add the desired standards support. That's why we provide this as Open Source.

**Comment by 06needhamt** [comment]
@tomjebo Thank you for your explanation. I'm not sure if this is possible but could we add a new validation type that tells us if a document is valid in terms of Office rather than the XML Schema? As one of my use cases is to simply check if a file is a valid document spreadsheet presentation etc when it is uploaded to our server and not some other file with the file extension changed to get past an extension filter.

**Comment by tomjebo** [comment]
@06needhamt The validations we have actually already validate in terms of Office (2007, 2010, 2013, 2016). That "line" enum is actually invalid for Office going back to the beginning wrt VML drawing. My last post was raising the discussion about something we've considered which is validation in terms of ISO 29500 strict and transitional schemas. 

If you're looking to find out if Office will or will not complain about a document, that is another question. In general, if it validates with the SDK's validation (for the specific version of Office you're using), then Office shouldn't complain. If there's a discrepancy in this respect, we should inspect our SDK processing and see if we need to adjust it per Office real behavior. However, in this case, our implementation notes make it clear that "Line" is not valid and Office should complain, that is, unless it has an alternate content block providing valid XML alongside the invalid XML.

Does that answer your question?

**Comment by 06needhamt** [comment]
@tomjebo Thank you for the response. This partially answers my question. The other part that I was asking about was just a simple check to see if a file is a valid document in the sense that it's not some other file e.g. a video renamed to a .docx file. I will open a separate issue for it as it's not related to this issue.

**Comment by 06needhamt** [comment]
Going to close this issue as I am satisfied with the responses. Feel free to reopen if necessary
