### ISSUE TITLE
Memory use when loading worksheets

### ISSUE THREAD

**Issue by zds0180** [OfficeDev/Open-XML-SDK#756]
I am seeing what I perceive to be excessive memory use when attempting to get the names of all of the worksheets in a workbook. As soon as I try and open the worksheets inside of the package (excelPackage.Workbook.Worksheets) my test uses ~ 400 MB of memory and takes around 20 seconds to finish that line of code. I am wondering if this is a normal amount of load for the tool to be using for a 30 MB .xlsx file with 3 worksheets. My larger issue is that the tool seems to be keeping around 1.2 GB of memory even after I am done with this ListWorksheets task. So a) 1.2 GB seems excessive for a 30 MB file and b) the memory should be deallocated when the tool is done with it should it not?

**Comment by twsouthwick** [comment]
Can you provide a bit more info? What versions of the SDK/Runtime/OS are you using?

I recently fixed a perf issue that will be fixed with .NET 5 System.IO.Packaging release (which will be supported on .NET Standard/Core as well, but not framework). If you have a repro, we can see if it'll be fixed there.
