### ISSUE TITLE
Undocumented information about the library

### ISSUE THREAD

**Issue by SoftCircuits** [OfficeDev/Open-XML-SDK#999]
### Description

I have two questions about working with OpenXML and Excel files. I realize this isn't an answer and question forum, but stackoverflow is complete useless for these type of questions. If someone happens to know the answers, that'd be great.

#### Order of Cells on Row
In the `InsertCellInWorksheet()` method in [this article](https://docs.microsoft.com/en-us/office/open-xml/how-to-insert-text-into-a-cell-in-a-spreadsheet), cells are added to a row sorted in order of each cell's `CellReference`. That means they are not sorted in the order they appear in the spreadsheet (for example, "AA1" would come before "Z1"). Can this actually be right way to sort cells in a row?

*Note: After doing research, I was able to confirm cells are not sorted alphabetically by reference within the row. The Microsoft example is just plain wrong. I'd be curious how others are handling this.*

#### Saving Changes
In the examples I found (including ones from Microsoft in the article linked above), I see `Save()` being called all over the place. For example, after creating a worksheet, `Workbook.Save()` is called. And after adding a shared string, `SharedStringTable.Save()` is called. Is this really necessary? If I don't save anything until calling `SpreadsheetDocument.Save()` at the very end, is there anything that might not be saved?

### Information
- .NET Target: .NET 5.0
- DocumentFormat.OpenXml Version: 2.13.0

**Comment by ThomasBarnekow** [comment]
Did you ask the question on stackoverflow.com at all?

Regarding your first question (Order of Cells on Row), yes, examples can be wrong (much like answers on stackoverflow.com for that matter). But it should not be surprising to order cells as they appear in the spreadsheet. Did you test what happens if the order is different? Did you inspect the Open XML markup created by Excel?

Regarding your second question (Saving Changes), you do **not** need to call `Save()` all over the place. In fact, in typical cases, you don't have to call `Save()` at all. If you open a `SpreadsheetDocument` (or other `OpenXmlPackage`) in a `using` statement, the loaded DOM trees will be saved automatically to the `OpenXmlPart`s when disposing of the `OpenXmlPackage`.

You'll only have to call `Save()` explicitly if you want to read data from the `OpenXmlPart` directly after having made changes to the DOM tree.

**Comment by SoftCircuits** [comment]
@ThomasBarnekow Thanks.

I've asked several related questions on stackoverflow and was not helped. Frankly, I think stackoverflow has gone downhill.

I did test the cell order on a row, but it was still surprising to learn an example on Microsoft's own website is so wrong.

Thanks for the info about Save. All of Microsoft's examples show it saving "all over the place." I will attempt to rework my code as you described.

**Comment by ThomasBarnekow** [comment]
@twsouthwick, we can close this issue.
